Vagrant.configure("2") do |config|
  config.vm.hostname = 'lazyTools-test'
  config.vm.box = "ubuntu/xenial64"
  config.vm.network :forwarded_port, host: 80, guest: 80
  # Load all lazyTools project into the default vagrant location named /vagrant
  config.vm.synced_folder "..", "/vagrant"                                                                                                                                                       

  # By default vagrant run shell command as root 
  # but we need to run setup.sh as the default vagrant user (s.priviliged)
  config.vm.provision "shell" do |s|
    s.inline = "cd /vagrant && sudo ./setup.sh"
    s.privileged = false
  end
end
